### ISSUE TITLE
dropzone.valid is not working in Chrome

### ISSUE THREAD

**Issue by krachtstefan** [tim-evans/ember-file-upload#104]
Hi there, 

I'm using the latest Chrome for Mac (64.0.3282.140) and I just noticed that the `dropzone.valid` equals true even if the file type doesn't match the accept-pattern. I tried it on your demo site to double check it. A file called `test` or `test.txt` succeeds even though the pattern is `accept="image/*,video/*,audio/*"`. Works fine in Firefox (58.0.1)

**Comment by tim-evans** [comment]
Oh dear. Could you write a test for this? I can try to fix this, but it may take a bit of time.

**Comment by mattmcmanus** [comment]
I'm currently debugging the same issue. I don't have a functioning test at the moment, but here is what I know!

It returns valid because the `dataTransfer` object has no files. So the valid check on length returns true, ie: `0 === 0`. 

```js
// data-transfer.js
return (
  get(this, 'dataTransfer.items.length') // 0
  get(this, 'dataTransfer.files.length')
) === get(this, 'files.length'); // 0
```

The original dragEvent dataTransfer item list **does** indeed have files. Something happens to the event after it's been scheduled to send by the `DragListener`.

```js
// drag-listener.js
scheduleEvent(eventName, listener, event) {
  ...
  this._events.push({ eventName, listener, event }); // event has items in dragEvent
  if (!this._scheduled) {
     this._scheduled = next(this, 'sendEvents');
  }
```

```js
// drag-listener.js
sendEvents(eventName, listener, event) {
  this._events.forEach(({ eventName, listener, event }) => {
    // event seems like same event object, but items is empty
...
```

Thats as far as I've gotten.

**Comment by lukemelia** [comment]
Looks related to https://bugs.chromium.org/p/chromium/issues/detail?id=137231#c1. `items` is not available outside the frame of the event.
