### ISSUE TITLE
I've been trying to make this work with firebase

### ISSUE THREAD

**Issue by Ghostavio** [tim-evans/ember-file-upload#38]
Using in conjunction with https://github.com/rmmmp/emberfire-utils#storage-manipulations
The major problem is trying to integrate with the `file.upload()` method, as I'm required to do this to upload to firebase: ```this.get('firebaseUtil').uploadFile(`images/${filename}`, file.blob).then(...)```. I'm trying to figure out how to integrate this two together, but I can't seem to make it work, any idea on how to do it?

**Comment by Ghostavio** [comment]
I managed to make it work with this
```
const progressBar = function(snapshot) {
  const progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;

  set(file, 'loaded', snapshot.bytesTransferred);
  set(file, 'size', snapshot.totalBytes);
  set(file, 'progress', progress);

  if (progress === 100) set(file, 'state', 'uploaded');
}
```

as `uploadFile` can also accept a method with the path and file to handle the progress, I pass `progressBar` and just handle the file state.

This works but it's not a very elegant solution, it would be nice to allow the user to use his own uploader method in cases like this.

**Comment by Ghostavio** [comment]
Anyway, I'm closing this. I hope this can help in case someone searchs for how to do it :)

**Comment by tim-evans** [comment]
Hmm. This is a bit tricky, since you're uploading over a different protocol (possibly). Your solution looks ok here- you don't *need* to use the `upload` method, but it does provide an easier way to upload for 95% of use cases that I've worked with. (I'm not sure how many apps use a different transport mechanism for uploading files other than XMLHttpRequests)
